### PR TITLE
change grey in subtitles

### LINKED ISSUE #31: is the contrast too low
the grey of the date/subtitle is quite light, hard to see on white?

### PR DESCRIPTION
**Pull request by chucheria**
fixes #31 

@maelle, could you build the site and take a look?

### CODE REVIEW

**Comment by maelle** [comment]
Could I use one of the preview links? It'd be easier if there were an online preview, then we could use https://color.a11y.com/

**Comment by chucheria** [comment]
do you want it black then?

**Comment by chucheria** [comment]
@maelle you can use: https://5eba67f321a0350006fb984a--stoic-curran-741947.netlify.app/ it is the built preview, let me know if it doesn't work for you

**Comment by maelle** [comment]
Thanks! Two color pairs have still too low contrast according to the contrast checker linked above (I discovered the tool recently, quite useful) 

Screenshot_20200512-180458

**Pull request closed without merging**
