### PR TITLE
updates to contributing guidelines

### PR DESCRIPTION
**Pull request by shannonpileggi**

### CODE REVIEW

**Comment by shannonpileggi** [comment]
still a WIP, will notify when ready for review!

**Comment by shannonpileggi** [comment]
The changes in this are:

README:

1. Remove technical details w/ forking and packages - save those for `CONTRIBUTING` doc
2. Removed manual toc - according to this [post](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/) I believe toc should be automatically generated.

**Comment by shannonpileggi** [comment]
@Athanasiamo updates to contributing guidelines are ready for review!

**Comment by Athanasiamo** [comment]
Thank you for much for this! 👏🏼 🎉 🥳  So thorough, so nice!

**Comment by shannonpileggi** [comment]
Super! @Athanasiamo, I didn't realize that the toc is something you have click on and does not populate in the readme. Just wanted to let you know in case it was something you felt strongly about.

**Comment by Athanasiamo** [comment]
nah, I dont really. So I'm happy with it without a toc, its so much improved from before!

**Pull request merged**
